const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{url:'https://timeline.test',runScripts:'outside-only'}),w=dom.window,d=w.document;
w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};
w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};
const event=(id,start,end,parentId=null)=>({id,title:id,start,end,parentId,notes:'',color:'blue'});
let events=[];
w.TIMELINE_CONFIG={provider:'supabase',supabaseUrl:'https://test.invalid',publishableKey:'test'};
w.fetch=async()=>({ok:true,json:async()=>({ok:true,events,supportsSubevents:true,supportsNestedEvents:true})});
w.eval(['dates.js','ids.js','app.js'].map(f=>fs.readFileSync(f,'utf8')).join('\n'));
const refresh=async(items)=>{events=items;d.querySelector('#refresh').click();await new Promise(r=>setTimeout(r,0));};
await new Promise(r=>setTimeout(r,0));
const bars=()=>Object.fromEntries([...d.querySelectorAll('.event-bar')].map(b=>[b.querySelector('strong').textContent,b]));
await refresh([event('A','-500','-400'),event('B','-400','-300'),event('Overlap','-450','-350'),event('Child','-480','-420','A'),event('Grandchild','-470','-460','Child')]);
let b=bars();
assert.equal(b.A.style.top,b.B.style.top,'Shared BCE year boundary uses one lane');
assert.notEqual(b.A.style.top,b.Overlap.style.top,'Overlapping periods use different lanes');
assert.ok(parseFloat(b.Child.style.top)>parseFloat(b.A.style.top));
assert.ok(parseFloat(b.Grandchild.style.top)>parseFloat(b.Child.style.top));
assert.ok(parseFloat(b.A.style.left)+parseFloat(b.A.style.width)<=parseFloat(b.B.style.left),'Adjacent cards do not cover each other');
await refresh([event('First','2026-01-01','2026-02-01'),event('Second','2026-02-01','2026-03-01'),event('Point','2026-02-15',''),event('Point2','2026-02-15','')]);
b=bars();assert.equal(b.First.style.top,b.Second.style.top,'Shared full-date boundary uses one lane');
assert.notEqual(b.Second.style.top,b.Point.style.top,'Point inside a period uses another lane');
assert.notEqual(b.Point.style.top,b.Point2.style.top,'Coincident points remain distinct');
b.First.click();assert.equal(d.querySelector('#detail-title').textContent,'First');
await refresh([event('Year','2026','2026'),event('WithinYear','2026-06-01','')]);
b=bars();assert.notEqual(b.Year.style.top,b.WithinYear.style.top,'Year-only end still includes dates within that year');
assert.ok([...d.querySelectorAll('input,textarea')].every(e=>e.getAttribute('spellcheck')==='false'));
assert.match(d.querySelector('#auth-dialog').textContent,/20 minut/);
w.close();console.log('Lanes passed: touching years/dates, overlaps, nesting, card bounds, point events, details and spellcheck.');
})();
