const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict');
(async()=>{const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{url:'https://timeline.test',runScripts:'outside-only'}),w=dom.window,d=w.document;
w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new w.Event('close'));};
let events=[{id:'a',title:'Root',start:'-600',end:'-300',parentId:null},{id:'b',title:'Period child',start:'-500',end:'-400',parentId:'a'},{id:'c',title:'Grandchild',start:'-450',end:'',parentId:'b',image:'https://example.com/picture.jpg'}].map(e=>({...e,notes:'',color:'blue',revision:e.id+'rev'}));let lastSave,lastDelete,deleteCalls=0;
w.TIMELINE_CONFIG={provider:'supabase',supabaseUrl:'https://test.invalid',publishableKey:'test'};
w.fetch=async(url,args)=>{const p=JSON.parse(args.body).payload;if(p.action==='save'){lastSave=p.event;events=events.filter(e=>e.id!==p.event.id);events.push({...p.event,revision:'new'});return {ok:true,json:async()=>({ok:true,event:events.at(-1)})};}if(p.action==='delete'){deleteCalls++;lastDelete=p;const ids=Object.keys(p.descendantRevisions);events=events.filter(e=>e.id!==p.id && !(p.childrenMode==='delete'&&ids.includes(e.id))).map(e=>ids.includes(e.id)?{...e,parentId:null,revision:'detached'}:e);return {ok:true,json:async()=>({ok:true,events})};}return {ok:true,json:async()=>p.action==='list'?{ok:true,events,supportsSubevents:true,supportsNestedEvents:true,supportsImages:true}:{ok:true}};};
w.eval(['dates.js','ids.js','app.js'].map(f=>fs.readFileSync(f,'utf8')).join('\n'));const flush=()=>new Promise(r=>setTimeout(r,0));const auth=async()=>{if(d.querySelector('#auth-dialog').open){d.querySelector('#password').value='test-only';d.querySelector('#auth-form').dispatchEvent(new w.Event('submit',{cancelable:true}));await flush();}};await flush();
assert.equal(d.querySelectorAll('.event-bar').length,3);assert.equal(d.querySelectorAll('.event-image').length,1);
d.querySelector('#search').value='Grandchild';d.querySelector('#search').dispatchEvent(new w.Event('input'));assert.equal(d.querySelectorAll('.event-bar').length,3,'Search includes all ancestors');d.querySelector('#search').value='';d.querySelector('#search').dispatchEvent(new w.Event('input'));
d.querySelectorAll('.event-bar')[1].click();assert.equal(d.querySelector('#add-child').hidden,false,'Child period can have children');assert.equal(d.querySelector('#delete').disabled,false);d.querySelector('#add-child').click();await auth();assert.equal(d.querySelector('#parent-id').value,'b');const parentOptions=[...d.querySelector('#parent-id').options];assert.deepEqual(parentOptions.map(o=>o.value),['','a','b','c']);assert.equal(parentOptions.at(-1).disabled,true);assert.match(parentOptions[2].textContent,/Root.*Period child/);d.querySelector('#edit-dialog').close();
d.querySelector('.event-bar').click();d.querySelector('#edit').click();await auth();assert.equal(d.querySelector('#parent-id').querySelector('[value=b]'),null);assert.equal(d.querySelector('#parent-id').querySelector('[value=c]'),null);d.querySelector('#edit-dialog').close();
d.querySelector('#add').click();const f=d.querySelector('#edit-form');f.elements.title.value='New nested';f.elements.start.value='-460';f.elements.start.dispatchEvent(new w.Event('input'));assert.equal(d.querySelector('#parent-id').value,'b');const imageUrl=d.querySelector('#image-url');imageUrl.value='https://example.com/new.jpg';imageUrl.dispatchEvent(new w.Event('input'));assert.equal(d.querySelectorAll('#image-preview img').length,1);f.dispatchEvent(new w.Event('submit',{cancelable:true}));await flush();assert.equal(lastSave.parentId,'b');assert.equal(lastSave.image,'https://example.com/new.jpg');
d.querySelector('.event-bar').click();d.querySelector('#delete').click();assert.equal(d.querySelector('#delete-dialog').open,true);assert.equal(d.querySelector('#delete-options').hidden,false);d.querySelector('#delete-form').dispatchEvent(new w.Event('submit',{cancelable:true}));await flush();assert.equal(deleteCalls,0);assert.match(d.querySelector('#delete-error').textContent,/Izberi/);
d.querySelector('[name=childrenMode][value=detach]').checked=true;d.querySelector('#delete-form').dispatchEvent(new w.Event('submit',{cancelable:true}));await flush();assert.equal(lastDelete.childrenMode,'detach');assert.equal(Object.keys(lastDelete.descendantRevisions).length,3);assert.equal(events.length,3);assert.ok(events.every(e=>!e.parentId));assert.equal(events.find(e=>e.id==='c').image,'https://example.com/picture.jpg');
// Re-encode an uploaded file and remove it before saving.
d.querySelector('#add').click();w.Image=class{constructor(){this.width=2400;this.height=1600;}set src(value){queueMicrotask(()=>this.onload());}};w.HTMLCanvasElement.prototype.getContext=()=>({fillRect(){},drawImage(){}});w.HTMLCanvasElement.prototype.toDataURL=()=> 'data:image/jpeg;base64,AAAA';
const file=d.querySelector('#image-file');Object.defineProperty(file,'files',{value:[new w.File(['test'],'image.png',{type:'image/png'})],configurable:true});await file.onchange();assert.equal(d.querySelector('#image-preview img').getAttribute('src'),'data:image/jpeg;base64,AAAA');d.querySelector('#remove-image').click();assert.equal(d.querySelectorAll('#image-preview img').length,0);f.elements.title.value='No picture';f.elements.start.value='2000';f.dispatchEvent(new w.Event('submit',{cancelable:true}));await flush();assert.equal(lastSave.image,'');
// Cascade option sends every descendant and preserves unrelated events.
events.push(...[{id:'x',parentId:null,title:'Second root',start:'100',end:'200'},{id:'y',parentId:'x',title:'Second child',start:'120',end:'180'},{id:'z',parentId:'y',title:'Second grandchild',start:'150',end:''}].map(e=>({...e,color:'red',notes:'',revision:e.id+'rev'})));d.querySelector('#refresh').click();await flush();const root=[...d.querySelectorAll('.event-bar')].find(b=>b.textContent.includes('Second root'));root.click();d.querySelector('#delete').click();d.querySelector('[name=childrenMode][value=delete]').checked=true;d.querySelector('#delete-form').dispatchEvent(new w.Event('submit',{cancelable:true}));await flush();assert.equal(lastDelete.childrenMode,'delete');assert.deepEqual(Object.keys(lastDelete.descendantRevisions).sort(),['y','z']);assert.ok(!events.some(e=>['x','y','z'].includes(e.id)));assert.ok(events.some(e=>e.id==='c'));
w.close();console.log('Nested UI passed: recursive rendering/search, cycle-free parent options, automatic nested selection, images/upload/remove, deletion choice, flattening and cascading payloads.');})();
