const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{url:'https://timeline.test',runScripts:'outside-only'}),w=dom.window,d=w.document;
w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};
w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new w.Event('close'));};
let now=0,authCalls=0;w.performance.now=()=>now;
let events=[{id:'root',title:'Obdobje',start:'-500',end:'-400',notes:'',color:'blue',revision:'r1',parentId:null},{id:'child',title:'Bitka',start:'-450',end:'',notes:'Opis',color:'red',revision:'r2',parentId:'root'}],lastSaved;
w.TIMELINE_CONFIG={provider:'supabase',supabaseUrl:'https://test.invalid',publishableKey:'test-public'};
w.fetch=async(url,args)=>{const p=JSON.parse(args.body).payload;if(p.action==='auth')authCalls++;if(p.action==='save'){lastSaved=p.event;const event={...p.event,revision:'new'};events=events.filter(e=>e.id!==event.id);events.push(event);return {ok:true,json:async()=>({ok:true,event})};}return {ok:true,json:async()=>p.action==='list'?{ok:true,events,supportsSubevents:true}:{ok:true}};};
w.eval(['dates.js','ids.js','app.js'].map(file=>fs.readFileSync(file,'utf8')).join('\n')); 
const flush=()=>new Promise(r=>setTimeout(r,0));const auth=async()=>{if(!d.querySelector('#auth-dialog').open)return;d.querySelector('#password').value='test-only';d.querySelector('#auth-form').dispatchEvent(new w.Event('submit',{cancelable:true}));await flush();};await flush();
assert.equal(d.querySelector('#count').textContent,'2');assert.equal(d.querySelectorAll('.event-bar.subevent').length,1);
d.querySelector('.event-bar').click();assert.equal(d.querySelectorAll('.child-detail').length,1);assert.equal(d.querySelector('#delete').disabled,true);assert.equal(d.querySelector('#add-child').hidden,false);
d.querySelector('#add-child').click();await auth();assert.equal(d.querySelector('#parent-id').value,'root');assert.match(d.querySelector('#parent-help').textContent,/500/);
const f=d.querySelector('#edit-form');f.elements.title.value='Nova bitka';f.elements.start.value='-399';f.dispatchEvent(new w.Event('submit',{cancelable:true}));await flush();assert.equal(lastSaved,undefined);assert.match(d.querySelector('#edit-error').textContent,/znotraj/);
f.elements.start.value='-420';f.dispatchEvent(new w.Event('submit',{cancelable:true}));await flush();assert.equal(lastSaved.parentId,'root');assert.equal(lastSaved.start,'-420');assert.equal(d.querySelector('#count').textContent,'3');
d.querySelector('#search').value='Bitka';d.querySelector('#search').dispatchEvent(new w.Event('input'));assert.equal(d.querySelectorAll('.event-bar').length,3);assert.equal(d.querySelector('.event-bar strong').textContent,'Obdobje');
d.querySelector('#list-view').click();assert.equal(d.querySelectorAll('.list-event.subevent').length,2);
d.querySelector('.list-event.subevent').click();assert.equal(d.querySelector('#add-child').hidden,true);assert.equal(d.querySelector('#detail-parent').textContent,'↳ Obdobje');
d.querySelector('#edit').click();await auth();assert.equal(d.querySelector('#parent-id').value,'root');d.querySelector('#parent-id').value='';f.dispatchEvent(new w.Event('submit',{cancelable:true}));await flush();assert.equal(lastSaved.parentId,'');
assert.equal(authCalls,1,'Editor close and subsequent edits reuse the ten-minute unlock');
d.querySelector('#add').click();assert.equal(d.querySelector('#auth-dialog').open,false);assert.equal(d.querySelector('#edit-dialog').open,true);
f.elements.title.value='Draft kept after expiry';f.elements.start.value='2026';now=600000;
f.dispatchEvent(new w.Event('submit',{cancelable:true}));await flush();assert.equal(d.querySelector('#auth-dialog').open,true,'Save after ten minutes requires authentication');assert.equal(lastSaved.title,'Bitka');
await auth();await flush();assert.equal(authCalls,2);assert.equal(lastSaved.title,'Draft kept after expiry');assert.equal(d.querySelector('#edit-dialog').open,false);
now=1199999;d.querySelector('#add').click();assert.equal(d.querySelector('#auth-dialog').open,false);d.querySelector('#edit-dialog').close();
now=1200000;d.querySelector('#add').click();assert.equal(d.querySelector('#auth-dialog').open,true,'Repeated use does not extend the deadline');
assert.equal(w.localStorage.length,0,'Editor password is never persisted');
w.close();console.log('Ten-minute auth passed: reuse, fixed expiry, reauthentication and draft preservation. UI passed: grouped timeline/list/search, child details, password flow, bounds, saving and unassigning.');
})();
